Feature Reservation Model and Controller
mahammad-mostafa/tesla-booking-back-end pull request #15
Opened 2024-01-26 09:05 UTC by 78fatemanazari

### Description
- Create reservation model
- Create reservation controller
- Create reservation endpoints
- Include jwt helper function 
- Create associations between user and reservation model

2024-01-26 20:25 UTC, demesameneshoa requested changes
Hi @78fatemanazari 🙋‍♂️, 

# ♻️    Status: Changes Required ⏺️  

You have done a great job on this ticket 🎫 , keep it up 👍 but there are some changes you need to make, you are almost there

## Top highlight 🎯

- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
- The User Authentication is implemented properly ✅ 
<img src="https://media.giphy.com/media/yoOotVRp4JMxVTEgDy/giphy.gif?cid=790b7611hcviz42reu4rmd2kk579z54erhtxxhidcx6pdips&ep=v1_gifs_search&rid=giphy.gif&ct=g"/>

## Optional suggestionsgp

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2024-01-26 20:25 UTC, demesameneshoa commented on app/models/reservation.rb
- [ ] Please add a validation to the model attributes, so that the api can catch any wrongful inputs

2024-01-26 22:21 UTC, 78fatemanazari commented on app/models/reservation.rb
Thank you so much @demesameneshoa 
I will make these changes!

2024-01-28 19:50 UTC, demesameneshoa commented
Hi @78fatemanazari , 

Your ticket is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
-  Model, Controller and End points created properly  ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------

2024-01-28 19:50 UTC, demesameneshoa approved these changes
Hi @78fatemanazari , 

Your ticket is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
-  Model, Controller and End points created properly  ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------

2024-01-28 20:20 UTC, merged